### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Mte90** [mkusher/padawan.php#114]
Seems similar to #27 but the errors is completely different.

```PHP Fatal error:  Uncaught Error: Call to undefined method Padawan\Domain\Scope\FunctionScope::addClass() in /opt/padawan/padawan.php/src/Padawan/Domain/Scope/ClassScope.php:26
Stack trace:
#0 /opt/padawan/padawan.php/src/Padawan/Parser/Walker/IndexGeneratingWalker.php(63): Padawan\Domain\Scope\ClassScope->__construct(Object(Padawan\Domain\Scope\FunctionScope), Object(Padawan\Domain\Project\Node\ClassData))
#1 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): Padawan\Parser\Walker\IndexGeneratingWalker->enterNode(Object(PhpParser\Node\Stmt\Class_))
#2 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#3 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Function_))
#4 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#5 /opt/pada in /opt/padawan/padawan.php/src/Padawan/Domain/Scope/ClassScope.php on line 26
Fatal error: Uncaught Error: Call to undefined method Padawan\Domain\Scope\FunctionScope::addClass() in /opt/padawan/padawan.php/src/Padawan/Domain/Scope/ClassScope.php:26
Stack trace:
#0 /opt/padawan/padawan.php/src/Padawan/Parser/Walker/IndexGeneratingWalker.php(63): Padawan\Domain\Scope\ClassScope->__construct(Object(Padawan\Domain\Scope\FunctionScope), Object(Padawan\Domain\Project\Node\ClassData))
#1 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): Padawan\Parser\Walker\IndexGeneratingWalker->enterNode(Object(PhpParser\Node\Stmt\Class_))
#2 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#3 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Function_))
#4 /opt/padawan/padawan.php/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#5 /opt/pada in /opt/padawan/padawan.php/src/Padawan/Domain/Scope/ClassScope.php on line 26```

**Comment by Mte90** [comment]
Seems that happen with an huge amount of files

**Comment by mkusher** [comment]
hm, looks like some unhandled situation, maybe with anonymous classes inside functions
