### ISSUE TITLE
Unable to generate structure since latest update

### ISSUE THREAD

**Issue by MichaelMackus** [mkusher/padawan.php#27]
Getting this error on padawan generate:

```
PHP Fatal error:  Call to undefined method Padawan\Domain\Core\Completion\Scope\ClassScope::addClass() in /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Domain/Co
re/Completion/Scope/ClassScope.php on line 26
PHP Stack trace:
PHP   1. {main}() /home/michael/.composer/vendor/mkusher/padawan/bin/padawan:0
PHP   2. Symfony\Component\Console\Application->run() /home/michael/.composer/vendor/mkusher/padawan/bin/padawan:27
PHP   3. Symfony\Component\Console\Application->doRun() /home/michael/.composer/vendor/symfony/console/Application.php:123
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/michael/.composer/vendor/symfony/console/Application.php:192
PHP   5. Symfony\Component\Console\Command\Command->run() /home/michael/.composer/vendor/symfony/console/Application.php:844
PHP   6. Padawan\Framework\Application\CLI\GenerateCommand->execute() /home/michael/.composer/vendor/symfony/console/Command/Command.php:259
PHP   7. Padawan\Framework\Generator\IndexGenerator->generateIndex() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Application/CLI/GenerateCommand.php:
39
PHP   8. Padawan\Framework\Generator\IndexGenerator->generateProjectIndex() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:
47
PHP   9. Padawan\Framework\Generator\IndexGenerator->processFile() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:65
PHP  10. Padawan\Framework\Generator\IndexGenerator->createScopeForFile() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:92
PHP  11. Padawan\Parser\Parser->parseFile() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:103
PHP  12. Padawan\Parser\Parser->parseContent() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php:36
PHP  13. PhpParser\NodeTraverser->traverse() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php:71
PHP  14. PhpParser\NodeTraverser->traverseArray() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:64
PHP  15. Padawan\Parser\Walker\IndexGeneratingWalker->enterNode() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:120
PHP  16. Padawan\Domain\Core\Completion\Scope\ClassScope->__construct() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Walker/IndexGeneratingWalker.php:64
```

**Comment by mkusher** [comment]
ouch, my fault :(

**Comment by mkusher** [comment]
@MichaelMackus can you test with https://github.com/mkusher/padawan.php/pull/28

**Comment by MichaelMackus** [comment]
@mkusher not sure if seperate issue, but when I checkout your branch I get this error (but 93% progress at least):

```
[2016-04-08 10:32:35] completer.INFO: Progress: 93% [] []
[2016-04-08 10:32:35] completer.INFO: processing vendor/symfony/symfony/src/Symfony/Component/VarDumper/Tests/Fixtures/GeneratorDemo.php [] []
[2016-04-08 10:32:35] completer.DEBUG: Cache status: disabled [] []
[2016-04-08 10:32:35] completer.ERROR: Parsing failed in file /home/michael/work/colorescience/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Tests/Fixtures/GeneratorDemo.php  [] []
[2016-04-08 10:32:35] completer.ERROR: exception 'PhpParser\Error' with message 'Syntax error, unexpected T_STRING, expecting ';' on line 14' in /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:275 Stack trace: #0 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php(57): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...') #1 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php(36): Padawan\Parser\Parser->parseContent('/home/michael/w...', '<?php\n\nnamespac...', NULL, false) #2 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php(103): Padawan\Parser\Parser->parseFile('vendor/symfony/...', NULL, false) #3 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php(92): Padawan\Framework\Generator\IndexGenerator->createScopeForFile('vendor/symfony/...', Object(Padawan\Domain\Core\Index), false) #4 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php(65): Padawan\Framework\Generator\IndexGenerator->processFile(Object(Padawan\Domain\Core\Index), 'vendor/symfony/...', false, false) #5 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php(47): Padawan\Framework\Generator\IndexGenerator->generateProjectIndex(Object(Padawan\Domain\Core\Project)) #6 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Application/CLI/GenerateCommand.php(39): Padawan\Framework\Generator\IndexGenerator->generateIndex(Object(Padawan\Domain\Core\Project)) #7 /home/michael/.composer/vendor/symfony/console/Command/Command.php(259): Padawan\Framework\Application\CLI\GenerateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /home/michael/.composer/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /home/michael/.composer/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Padawan\Framework\Application\CLI\GenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /home/michael/.composer/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /home/michael/.composer/vendor/mkusher/padawan/bin/padawan(27): Symfony\Component\Console\Application->run() #12 {main} [] []
[2016-04-08 10:32:35] completer.INFO: Parsing: [0.0056610107421875]s [] []
[2016-04-08 10:32:35] completer.DEBUG: Indexing: [0.0062088966369629]s [] []
[2016-04-08 10:32:35] completer.DEBUG: Memory: 805490480 [] []
[2016-04-08 10:32:35] completer.INFO: Progress: 93% [] []
[2016-04-08 10:32:35] completer.INFO: processing vendor/symfony/symfony/src/Symfony/Component/VarDumper/Tests/Fixtures/Twig.php [] []
[2016-04-08 10:32:35] completer.DEBUG: Cache status: disabled [] []
[2016-04-08 10:32:35] completer.INFO: Traversing with 2 walkers [] []
[2016-04-08 10:32:35] completer.INFO: Parsing: [0.011126041412354]s [] []
Array
(
    [0] => Padawan\Domain\Core\Completion\Scope\FileScope Object
        (
            [classes:Padawan\Domain\Core\Completion\Scope\FileScope:private] => Array
                (
                    [__TwigTemplate_VarDumperFixture_u75a09] => Padawan\Domain\Core\Node\ClassData Object
                        (
                            [interfaces] => Array
                                (
                                )

                            [uses] => 
                            [fqcn] => Padawan\Domain\Core\FQCN Object
                                (
                                    [_isArray:Padawan\Domain\Core\FQCN:private] => 
                                    [_isScalar:Padawan\Domain\Core\FQCN:private] => 
                                    [parts:Padawan\Domain\Core\FQN:private] => Array
                                        (
                                            [0] => __TwigTemplate_VarDumperFixture_u75a09
                                        )

                                )

                            [doc] =>  foo.twig 
                            [startLine] => 4
                            [file] => /home/michael/work/colorescience/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Tests/Fixtures/Twig.php
                            [parent:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\FQCN Object
                                (
                                    [_isArray:Padawan\Domain\Core\FQCN:private] => 
                                    [_isScalar:Padawan\Domain\Core\FQCN:private] => 
                                    [parts:Padawan\Domain\Core\FQN:private] => Array
                                        (
                                            [0] => Twig_Template
                                        )

                                )

                            [methods:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\Collection\MethodsCollection Object
                                (
                                    [methods:Padawan\Domain\Core\Collection\MethodsCollection:private] => Array
                                        (
                                            [__construct] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => __construct
                                                    [arguments] => Array
                                                        (
                                                            [env] => Padawan\Domain\Core\Node\MethodParam Object
                                                                (
                                                                    [default] => 
                                                                    [name:Padawan\Domain\Core\Node\Variable:private] => env
                                                                    [fqcn:Padawan\Domain\Core\Node\Variable:private] => Padawan\Domain\Core\FQCN Object
                                                                        (
                                                                            [_isArray:Padawan\Domain\Core\FQCN:private] => 
                                                                            [_isScalar:Padawan\Domain\Core\FQCN:private] => 
                                                                            [parts:Padawan\Domain\Core\FQN:private] => Array
                                                                                (
                                                                                    [0] => Twig_Environment
                                                                                )

                                                                        )

                                                                )

                                                        )

                                                    [doc] => 
                                                    [type] => 1
                                                    [startLine] => 6
                                                    [endLine] => 14
                                                    [return] => 
                                                )

                                            [doDisplay] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => doDisplay
                                                    [arguments] => Array
                                                        (
                                                            [context] => Padawan\Domain\Core\Node\MethodParam Object
                                                                (
                                                                    [default] => 
                                                                    [name:Padawan\Domain\Core\Node\Variable:private] => context
                                                                    [fqcn:Padawan\Domain\Core\Node\Variable:private] => array
                                                                )

                                                            [blocks] => Padawan\Domain\Core\Node\MethodParam Object
                                                                (
                                                                    [default] => 
                                                                    [name:Padawan\Domain\Core\Node\Variable:private] => blocks
                                                                    [fqcn:Padawan\Domain\Core\Node\Variable:private] => array
                                                                )

                                                        )

                                                    [doc] => 
                                                    [type] => 2
                                                    [startLine] => 16
                                                    [endLine] => 20
                                                    [return] => 
                                                )

                                            [getTemplateName] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => getTemplateName
                                                    [arguments] => Array
                                                        (
                                                        )

                                                    [doc] => 
                                                    [type] => 1
                                                    [startLine] => 22
                                                    [endLine] => 25
                                                    [return] => 
                                                )

                                            [getDebugInfo] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => getDebugInfo
                                                    [arguments] => Array
                                                        (
                                                        )

                                                    [doc] => 
                                                    [type] => 1
                                                    [startLine] => 27
                                                    [endLine] => 30
                                                    [return] => 
                                                )

                                        )

                                    [class:Padawan\Domain\Core\Collection\MethodsCollection:private] => Padawan\Domain\Core\Node\ClassData Object
 *RECURSION*
                                )

                            [properties:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\Collection\PropertiesCollection Object
                                (
                                    [map:Padawan\Domain\Core\Collection\PropertiesCollection:private] => Array
                                        (
                                        )

                                    [class:Padawan\Domain\Core\Collection\PropertiesCollection:private] => Padawan\Domain\Core\Node\ClassData Object
 *RECURSION*
                                )

                            [constants:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\Collection\ConstCollection Object
                                (
                                    [map:Padawan\Domain\Core\Collection\ConstCollection:private] => Array
                                        (
                                            [class] => class
                                        )

                                    [class:Padawan\Domain\Core\Collection\ConstCollection:private] => Padawan\Domain\Core\Node\ClassData Object
 *RECURSION*
                                )

                        )

                )

            [interfaces:Padawan\Domain\Core\Completion\Scope\FileScope:private] => Array
                (
                )

            [namespace:Padawan\Domain\Core\Completion\Scope\FileScope:private] => 
            [uses:Padawan\Domain\Core\Completion\Scope\FileScope:private] => Padawan\Domain\Core\Node\Uses Object
                (
                    [map:Padawan\Domain\Core\Node\Uses:private] => Array
                        (
                        )

                    [reversed:Padawan\Domain\Core\Node\Uses:private] => 
                    [fqcn:Padawan\Domain\Core\Node\Uses:private] => Padawan\Domain\Core\FQN Object
                        (
                            [parts:Padawan\Domain\Core\FQN:private] => Array
                                (
                                )

                        )

                )

            [variables:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => Array
                (
                )

            [functions:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => Array
                (
                )

            [constants:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => Array
                (
                )

            [parent:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => 
        )

    [1] => Padawan\Domain\Core\Completion\Scope\FileScope Object
        (
            [classes:Padawan\Domain\Core\Completion\Scope\FileScope:private] => Array
                (
                    [__TwigTemplate_VarDumperFixture_u75a09] => Padawan\Domain\Core\Node\ClassData Object
                        (
                            [interfaces] => Array
                                (
                                )

                            [uses] => 
                            [fqcn] => Padawan\Domain\Core\FQCN Object
                                (
                                    [_isArray:Padawan\Domain\Core\FQCN:private] => 
                                    [_isScalar:Padawan\Domain\Core\FQCN:private] => 
                                    [parts:Padawan\Domain\Core\FQN:private] => Array
                                        (
                                            [0] => __TwigTemplate_VarDumperFixture_u75a09
                                        )

                                )

                            [doc] =>  foo.twig 
                            [startLine] => 4
                            [file] => /home/michael/work/colorescience/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Tests/Fixtures/Twig.php
                            [parent:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\FQCN Object
                                (
                                    [_isArray:Padawan\Domain\Core\FQCN:private] => 
                                    [_isScalar:Padawan\Domain\Core\FQCN:private] => 
                                    [parts:Padawan\Domain\Core\FQN:private] => Array
                                        (
                                            [0] => Twig_Template
                                        )

                                )

                            [methods:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\Collection\MethodsCollection Object
                                (
                                    [methods:Padawan\Domain\Core\Collection\MethodsCollection:private] => Array
                                        (
                                            [__construct] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => __construct
                                                    [arguments] => Array
                                                        (
                                                            [env] => Padawan\Domain\Core\Node\MethodParam Object
                                                                (
                                                                    [default] => 
                                                                    [name:Padawan\Domain\Core\Node\Variable:private] => env
                                                                    [fqcn:Padawan\Domain\Core\Node\Variable:private] => Padawan\Domain\Core\FQCN Object
                                                                        (
                                                                            [_isArray:Padawan\Domain\Core\FQCN:private] => 
                                                                            [_isScalar:Padawan\Domain\Core\FQCN:private] => 
                                                                            [parts:Padawan\Domain\Core\FQN:private] => Array
                                                                                (
                                                                                    [0] => Twig_Environment
                                                                                )

                                                                        )

                                                                )

                                                        )

                                                    [doc] => 
                                                    [type] => 1
                                                    [startLine] => 6
                                                    [endLine] => 14
                                                    [return] => 
                                                )

                                            [doDisplay] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => doDisplay
                                                    [arguments] => Array
                                                        (
                                                            [context] => Padawan\Domain\Core\Node\MethodParam Object
                                                                (
                                                                    [default] => 
                                                                    [name:Padawan\Domain\Core\Node\Variable:private] => context
                                                                    [fqcn:Padawan\Domain\Core\Node\Variable:private] => array
                                                                )

                                                            [blocks] => Padawan\Domain\Core\Node\MethodParam Object
                                                                (
                                                                    [default] => 
                                                                    [name:Padawan\Domain\Core\Node\Variable:private] => blocks
                                                                    [fqcn:Padawan\Domain\Core\Node\Variable:private] => array
                                                                )

                                                        )

                                                    [doc] => 
                                                    [type] => 2
                                                    [startLine] => 16
                                                    [endLine] => 20
                                                    [return] => 
                                                )

                                            [getTemplateName] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => getTemplateName
                                                    [arguments] => Array
                                                        (
                                                        )

                                                    [doc] => 
                                                    [type] => 1
                                                    [startLine] => 22
                                                    [endLine] => 25
                                                    [return] => 
                                                )

                                            [getDebugInfo] => Padawan\Domain\Core\Node\MethodData Object
                                                (
                                                    [name] => getDebugInfo
                                                    [arguments] => Array
                                                        (
                                                        )

                                                    [doc] => 
                                                    [type] => 1
                                                    [startLine] => 27
                                                    [endLine] => 30
                                                    [return] => 
                                                )

                                        )

                                    [class:Padawan\Domain\Core\Collection\MethodsCollection:private] => Padawan\Domain\Core\Node\ClassData Object
 *RECURSION*
                                )

                            [properties:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\Collection\PropertiesCollection Object
                                (
                                    [map:Padawan\Domain\Core\Collection\PropertiesCollection:private] => Array
                                        (
                                        )

                                    [class:Padawan\Domain\Core\Collection\PropertiesCollection:private] => Padawan\Domain\Core\Node\ClassData Object
 *RECURSION*
                                )

                            [constants:Padawan\Domain\Core\Node\ClassData:private] => Padawan\Domain\Core\Collection\ConstCollection Object
                                (
                                    [map:Padawan\Domain\Core\Collection\ConstCollection:private] => Array
                                        (
                                            [class] => class
                                        )

                                    [class:Padawan\Domain\Core\Collection\ConstCollection:private] => Padawan\Domain\Core\Node\ClassData Object
 *RECURSION*
                                )

                        )

                )

            [interfaces:Padawan\Domain\Core\Completion\Scope\FileScope:private] => Array
                (
                )

            [namespace:Padawan\Domain\Core\Completion\Scope\FileScope:private] => 
            [uses:Padawan\Domain\Core\Completion\Scope\FileScope:private] => Padawan\Domain\Core\Node\Uses Object
                (
                    [map:Padawan\Domain\Core\Node\Uses:private] => Array
                        (
                        )

                    [reversed:Padawan\Domain\Core\Node\Uses:private] => 
                    [fqcn:Padawan\Domain\Core\Node\Uses:private] => Padawan\Domain\Core\FQN Object
                        (
                            [parts:Padawan\Domain\Core\FQN:private] => Array
                                (
                                )

                        )

                )

            [variables:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => Array
                (
                )

            [functions:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => Array
                (
                )

            [constants:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => Array
                (
                )

            [parent:Padawan\Domain\Core\Completion\Scope\AbstractScope:private] => 
        )

)
```

**Comment by MichaelMackus** [comment]
Sorry, here's the actual PHP error (there's lots of these, just Warnings though, I didn't see any Fatal errors):

```
PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Domain/Core/Collection/PropertiesCollection.php on line 52
PHP Stack trace:
PHP   1. {main}() /home/michael/.composer/vendor/mkusher/padawan/bin/padawan:0
PHP   2. Symfony\Component\Console\Application->run() /home/michael/.composer/vendor/mkusher/padawan/bin/padawan:27
PHP   3. Symfony\Component\Console\Application->doRun() /home/michael/.composer/vendor/symfony/console/Application.php:123
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/michael/.composer/vendor/symfony/console/Application.php:192
PHP   5. Symfony\Component\Console\Command\Command->run() /home/michael/.composer/vendor/symfony/console/Application.php:844
PHP   6. Padawan\Framework\Application\CLI\GenerateCommand->execute() /home/michael/.composer/vendor/symfony/console/Command/Command.php:259
PHP   7. Padawan\Framework\Generator\IndexGenerator->generateIndex() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Application/CLI/GenerateCommand.php:39
PHP   8. Padawan\Framework\Generator\IndexGenerator->generateProjectIndex() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:47
PHP   9. Padawan\Framework\Generator\IndexGenerator->processFile() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:65
PHP  10. Padawan\Framework\Generator\IndexGenerator->createScopeForFile() /home/michael
/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:92
PHP  11. Padawan\Parser\Parser->parseFile() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php:103
PHP  12. Padawan\Parser\Parser->parseContent() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php:36
PHP  13. PhpParser\NodeTraverser->traverse() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php:71
PHP  14. PhpParser\NodeTraverser->traverseArray() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:64
PHP  15. PhpParser\NodeTraverser->traverseNode() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  16. PhpParser\NodeTraverser->traverseArray() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  17. PhpParser\NodeTraverser->traverseNode() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  18. PhpParser\NodeTraverser->traverseArray() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  19. PhpParser\NodeTraverser->traverseNode() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  20. PhpParser\NodeTraverser->traverseArray() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  21. Padawan\Parser\Walker\IndexGeneratingWalker->leaveNode() /home/michael/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:133
PHP  22. Padawan\Parser\Transformer\ClassAssignmentTransformer->transform() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Walker/IndexGeneratingWalker.php:111
PHP  23. Padawan\Domain\Core\Node\ClassData->hasProp() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Transformer/ClassAssignmentTransformer.php:33
PHP  24. Padawan\Domain\Core\Collection\PropertiesCollection->get() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Domain/Core/Node/ClassData.php:106
PHP  25. array_key_exists() /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Domain/Core/Collection/PropertiesCollection.php:52
```

**Comment by mkusher** [comment]
@MichaelMackus and was index generated successfully?

**Comment by MichaelMackus** [comment]
No :(

No change in the .padawan/project timestamp

**Comment by mkusher** [comment]
@MichaelMackus ok, will check what happens in Twig...

**Comment by mkusher** [comment]
@MichaelMackus I tried indexing project with Twig and big symfony project, both with and without xdebug enabled. Maybe you can share files on which padawan throws errors?
Update: Found, indexing is failing on php 5.6

**Comment by mkusher** [comment]
@MichaelMackus check #28 one more time, I think I've managed to fix the issue

**Comment by mkusher** [comment]
@MichaelMackus I've merged this pr to master, so checkout latest padawan and try again. Reopen if issue is still valid
