### ISSUE TITLE
Parser error when generating index

### ISSUE THREAD

**Issue by MichaelMackus** [mkusher/padawan.php#32]
Doesn't generate successful index (haven't had an updated index since March 31st :()

Looks like some syntax error:

```
[2016-05-06 10:00:41] completer.ERROR: Parsing failed in file /home/michael/work/colorescience/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Tests/Fixtures/G[5/1924]
Demo.php  [] []
[2016-05-06 10:00:41] completer.ERROR: exception 'PhpParser\Error' with message 'Syntax error, unexpected T_STRING, expecting ';' on line 14' in /home/michael/.composer/vendo
r/nikic/php-parser/lib/PhpParser/ParserAbstract.php:275 Stack trace: #0 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php(57): PhpParser\ParserAbst
ract->parse('<?php\n\nnamespac...') #1 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Parser/Parser.php(36): Padawan\Parser\Parser->parseContent('/home/michael/w.
..', '<?php\n\nnamespac...', NULL, false) #2 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php(103): Padawan\Parser\Parser->pa
rseFile('vendor/symfony/...', NULL, false) #3 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php(92): Padawan\Framework\Generat
or\IndexGenerator->createScopeForFile('vendor/symfony/...', Object(Padawan\Domain\Core\Index), false) #4 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/
Generator/IndexGenerator.php(65): Padawan\Framework\Generator\IndexGenerator->processFile(Object(Padawan\Domain\Core\Index), 'vendor/symfony/...', false, false) #5 /home/mich
ael/.composer/vendor/mkusher/padawan/src/Padawan/Framework/Generator/IndexGenerator.php(47): Padawan\Framework\Generator\IndexGenerator->generateProjectIndex(Object(Padawan\D
omain\Core\Project)) #6 /home/michael/.composer/vendor/mkusher/padawan/src/Padawan/Command/GenerateCommand.php(39): Padawan\Framework\Generator\IndexGenerator->generateIndex(
Object(Padawan\Domain\Core\Project)) #7 /home/michael/.composer/vendor/symfony/console/Command/Command.php(259): Padawan\Command\GenerateCommand->execute(Object(Symfony\Compo
nent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /home/michael/.composer/vendor/symfony/console/Application.php(844): Symfony\Compone
nt\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /home/michael/.composer/vendor/s
ymfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Padawan\Command\GenerateCommand), Object(Symfony\Component\Console\Input\ArgvI
nput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /home/michael/.composer/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application-
>doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /home/michael/.composer/vendor/mkusher/padawan/bin/padaw
an(26): Symfony\Component\Console\Application->run() #12 {main} [] []
```

**Comment by mkusher** [comment]
@MichaelMackus 

``` php
<?php

namespace Symfony\Component\VarDumper\Tests\Fixtures;

class GeneratorDemo
{
    public static function foo()
    {
        yield 1;
    }

    public function baz()
    {
        yield from bar();
    }
}

function bar()
{
    yield from GeneratorDemo::foo();
}
```

looks like you have php 5.6 or less local, I think I need to just skip files with error...

**Comment by mkusher** [comment]
@MichaelMackus test with https://github.com/mkusher/padawan.php/pull/33

**Comment by mkusher** [comment]
@MichaelMackus have you got a chance to test index generation with latest master?

**Comment by MichaelMackus** [comment]
@mkusher yes index generation works, but now my completion isn't working any more :(

This issue is fixed, at least.

**Comment by mkusher** [comment]
@MichaelMackus I guess you need to update editor's plugin(for vim https://github.com/mkusher/padawan.vim/tree/new-padawan-api)
