### ISSUE TITLE
Fatal error occurs when send "kill" command

### ISSUE THREAD

**Issue by musou1500** [mkusher/padawan.php#99]
When I send kill command to padawan-server, it occurs error below.
thank you.
```
PHP Fatal error:  Uncaught Error: Call to undefined method Command\KillCommand::getContainer() in /home/usrname/.config/composer/vendor/mkusher/padawan/src/Application/BaseApplication.php:31
Stack trace:
#0 /home/usrname/.config/composer/vendor/mkusher/padawan/src/Application/HTTP/App.php(23): Application\BaseApplication->handle(Object(React\Http\Request), Object(React\Http\Response), '')
#1 /home/usrname/.config/composer/vendor/mkusher/padawan/bin/padawan-server(69): Application\HTTP\App->handle(Object(React\Http\Request), Object(React\Http\Response), '')
#2 [internal function]: {closure}('')
#3 /home/usrname/.config/composer/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array)
#4 /home/usrname/.config/composer/vendor/react/http/src/Server.php(61): Evenement\EventEmitter->emit('data', Array)
#5 /home/usrname/.config/composer/vendor/react/http/src/Server.php(28): React\Http\Server->handleRequest(Object(React\Socket\Connection), Object(React\Http\Request), '')
#6 in /home/usrname/.config/composer/vendor/mkusher/padawan/src/Application/BaseApplication.php on line 31
Fatal error: Uncaught Error: Call to undefined method Command\KillCommand::getContainer() in /home/usrname/.config/composer/vendor/mkusher/padawan/src/Application/BaseApplication.php:31
Stack trace:
#0 /home/usrname/.config/composer/vendor/mkusher/padawan/src/Application/HTTP/App.php(23): Application\BaseApplication->handle(Object(React\Http\Request), Object(React\Http\Response), '')
#1 /home/usrname/.config/composer/vendor/mkusher/padawan/bin/padawan-server(69): Application\HTTP\App->handle(Object(React\Http\Request), Object(React\Http\Response), '')
#2 [internal function]: {closure}('')
#3 /home/usrname/.config/composer/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array)
#4 /home/usrname/.config/composer/vendor/react/http/src/Server.php(61): Evenement\EventEmitter->emit('data', Array)
#5 /home/usrname/.config/composer/vendor/react/http/src/Server.php(28): React\Http\Server->handleRequest(Object(React\Socket\Connection), Object(React\Http\Request), '')
#6 in /home/usrname/.config/composer/vendor/mkusher/padawan/src/Application/BaseApplication.php on line 31
```

**Comment by musou1500** [comment]
Sorry I installed v0.2.1.
